services:
  - type: web
    name: gbaka-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MAPBOX_TOKEN
        sync: false  # Tu dois l'ajouter manuellement dans Render
    autoDeploy: true
    healthCheckPath: /api/health